const mongoose = require('mongoose');
const { v4: uuidv4 } = require('uuid');

const streamSchema = new mongoose.Schema({
    streamerId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    title: { type: String, required: true, default: 'Untitled Stream' },
    description: { type: String, default: '' },
    // Stream key used by OBS to push RTMP
    streamKey: { type: String, unique: true, default: () => uuidv4() },
    // HLS URL generated by FFmpeg conversion
    hlsUrl: { type: String, default: '' },
    isLive: { type: Boolean, default: false },
    viewerCount: { type: Number, default: 0 },
    startedAt: { type: Date },
    endedAt: { type: Date },
    createdAt: { type: Date, default: Date.now }
});

module.exports = mongoose.model('Stream', streamSchema);
